version: "3.9"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    networks:
      - app_network

  mqtt_consumer:
    build:
      context: ./pantsbuild/mqtt-consumer
      dockerfile: Dockerfile
    depends_on:
      - mqtt_broker
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
